apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: restaurant
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'ms-auth'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: ['ms-auth-service:8081']
      - job_name: 'ms-maestros'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: ['ms-maestros-service:8082']
      - job_name: 'ms-ventas'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: ['ms-ventas-service:8083']
      - job_name: 'api-gateway'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: ['api-gateway-service:8080']
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  namespace: restaurant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
        - name: prometheus
          image: prom/prometheus:v2.51.2
          ports:
            - containerPort: 9090
          args:
            - "--config.file=/etc/prometheus/prometheus.yml"
            - "--storage.tsdb.retention.time=7d"
          volumeMounts:
            - name: config
              mountPath: /etc/prometheus
            - name: data
              mountPath: /prometheus
      volumes:
        - name: config
          configMap:
            name: prometheus-config
        - name: data
          persistentVolumeClaim:
            claimName: prometheus-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
  namespace: restaurant
spec:
  selector:
    app: prometheus
  ports:
    - port: 9090
      targetPort: 9090
