apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-maestros
  namespace: restaurant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-maestros
  template:
    metadata:
      labels:
        app: ms-maestros
    spec:
      containers:
        - name: ms-maestros
          image: restaurant/ms-core-maestros:1.0.0
          ports:
            - containerPort: 8082
          envFrom:
            - configMapRef:
                name: restaurant-config
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres-service:5432/db_maestros
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: restaurant-secrets
                  key: SPRING_DATASOURCE_PASSWORD
          startupProbe:
            httpGet:
              path: /actuator/health
              port: 8082
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 60
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8082
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8082
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: ms-maestros-service
  namespace: restaurant
spec:
  selector:
    app: ms-maestros
  ports:
    - port: 8082
      targetPort: 8082
