apiVersion: v1
kind: Secret
metadata:
  name: restaurant-secrets
  namespace: restaurant
type: Opaque
stringData:
  POSTGRES_PASSWORD: postgres
  SPRING_DATASOURCE_PASSWORD: postgres
  RABBITMQ_DEFAULT_USER: guest
  RABBITMQ_DEFAULT_PASS: guest
  RABBITMQ_ERLANG_COOKIE: restaurant-cookie-2024
  JWT_SECRET: clave-secreta-restaurant-2024-muy-larga-para-seguridad
  GRAFANA_ADMIN_PASSWORD: admin
  # SONAR_JDBC_PASSWORD: postgres  (SonarQube comentado)
